### ISSUE TITLE
Allowed number of groups for ActivitySegmentation

### ISSUE THREAD

**Issue by mmosc** [giuliowaitforitdavide/recsyslearn#22]
Hi!

As discussed, we should consistently define the number of allowed groups for the ActivitySegmentation. The code [only returns two groups](https://github.com/giuliowaitforitdavide/recsyslearn/blob/c01142be0a1433783208d307717b2fc74051a83f/recsyslearn/dataset/segmentations.py#L189), hence we should:
1. Change the [docstring](https://github.com/giuliowaitforitdavide/recsyslearn/blob/c01142be0a1433783208d307717b2fc74051a83f/recsyslearn/dataset/segmentations.py#L155)
2. Change the [raise](https://github.com/giuliowaitforitdavide/recsyslearn/blob/c01142be0a1433783208d307717b2fc74051a83f/recsyslearn/dataset/segmentations.py#L169)
3. Document this feature in [the docstring](https://github.com/giuliowaitforitdavide/recsyslearn/blob/c01142be0a1433783208d307717b2fc74051a83f/recsyslearn/dataset/segmentations.py#L146): We could change this to `The proportion of users wanted for every group. Its length should be either 1 or 2.`. Notice the change from `interaction` to `user`, as well.

Cheers!
Marta

**Comment by giuliowaitforitdavide** [comment]
Right now I think that fix the docs and the docs could be better. Should we think about adding this feature (using more groups) later?

**Comment by mmosc** [comment]
Yes, I agree. I guess you meant fix the code and the docs (without extending the number of groups).

**Comment by giuliowaitforitdavide** [comment]
Yep, done
