### ISSUE TITLE
Segmenting a dataset: info in the README

### ISSUE THREAD

**Issue by mmosc** [giuliowaitforitdavide/recsyslearn#3]
Hi @giuliowaitforitdavide !
In the README, you write 
> If you don't have the info about the groups, you can use the library itself to segment the dataset. The dataset has to be in the form of ``user, item, rank``.

but I think it should be 
> If you don't have the info about the groups, you can use the library itself to segment the dataset. The dataset has to be in the form of ``user, item, timestamp``.

Is that right?
Cheers, 
Marta

**Comment by mmosc** [comment]
Aaaah, now I see what you meant! 
I think this is kind of confusing, since `'rank'` is used for the ranked lists...

What about using the word `'rating'` for explicit feedback?

**Comment by giuliowaitforitdavide** [comment]
I like it, I will open a branch later

**Comment by giuliowaitforitdavide** [comment]
I fixed it in the `fix/docs` branch. I'm opening right now a pull request which I would like you to evaluate. You will see what I wrote in the `usage.rst` file inside the docs folder
